name: Update gist
on:
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 475c67af71e4b9abbd0492754ce0caef
          TIMEZONE: Asia/Seoul
      - uses: gautamkrishnar/keepalive-workflow@v2
